openapi: 3.0.0
info:
  title: API Documentation
  description: Descripción de la API
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor de desarrollo

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          description: ID del usuario
        name:
          type: string
          description: Nombre del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
        rol:
          type: string
          enum: [estudiante, tutor, padre]
          description: Rol del usuario
        fecha_registro:
          type: string
          format: date-time
          description: Fecha de registro del usuario
        resetPasswordToken:
          type: string
          description: Token para restablecer la contraseña
        resetPasswordExpires:
          type: string
          format: date-time
          description: Fecha de expiración del token de restablecimiento de contraseña
        emailVerificationToken:
          type: string
          description: Token para verificar el correo electrónico
        emailVerified:
          type: boolean
          description: Indica si el correo electrónico ha sido verificado

    Subject:
      type: object
      properties:
        id:
          type: integer
          description: ID de la materia
        name:
          type: string
          description: Nombre de la materia
        description:
          type: string
          description: Descripción de la materia
        name_teacher:
          type: string
          description: Nombre del profesor
        userId:
          type: integer
          description: ID del usuario

    Activity:
      type: object
      properties:
        id:
          type: integer
          description: ID de la actividad
        titulo:
          type: string
          description: Título de la actividad
        description:
          type: string
          description: Descripción de la actividad
        fecha_inicio:
          type: string
          format: date-time
          description: Fecha de inicio de la actividad
        fecha_fin:
          type: string
          format: date-time
          description: Fecha de fin de la actividad
        estado:
          type: string
          enum: [pendiente, en_progreso, completada]
          description: Estado de la actividad
        num_preguntas:
          type: integer
          description: Número de preguntas de la actividad
        prioridad_id:
          type: integer
          description: ID de la prioridad de la actividad
        user_id:
          type: integer
          description: ID del usuario
        subject_id:
          type: integer
          description: ID de la materia

    CreateActivityRequest:
      type: object
      properties:
        titulo:
          type: string
          description: Título de la actividad
        description:
          type: string
          description: Descripción de la actividad
        fecha_inicio:
          type: string
          format: date-time
          description: Fecha de inicio de la actividad
        fecha_fin:
          type: string
          format: date-time
          description: Fecha de fin de la actividad
        estado:
          type: string
          enum: [pendiente, en_progreso, completada]
          description: Estado de la actividad
        num_preguntas:
          type: integer
          description: Número de preguntas de la actividad
        prioridad_id:
          type: integer
          description: ID de la prioridad de la actividad
    Priority:
      type: object
      properties:
        id:
          type: integer
          description: ID de la prioridad
        nivel:
          type: string
          enum: [baja, media, alta]
          description: Nivel de la prioridad

security:
  - bearerAuth: []

paths:
  /sign-up:
    post:
      summary: Registro de usuario
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Nombre del usuario
                email:
                  type: string
                  description: Correo electrónico del usuario
                password:
                  type: string
                  description: Contraseña del usuario
      responses:
        '201':
          description: Usuario registrado exitosamente
        '400':
          description: Error en la solicitud

  /sign-in:
    post:
      summary: Iniciar sesión
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Correo electrónico del usuario
                password:
                  type: string
                  description: Contraseña del usuario
      responses:
        '200':
          description: Inicio de sesión exitoso
        '401':
          description: Credenciales inválidas

  /sign-out:
    post:
      summary: Cerrar sesión
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Cierre de sesión exitoso
        '401':
          description: No autorizado

  /session:
    get:
      summary: Validar sesión
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Sesión válida
        '401':
          description: No autorizado

  /request-password-reset:
    post:
      summary: Solicitar restablecimiento de contraseña
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Correo electrónico del usuario
      responses:
        '200':
          description: Solicitud de restablecimiento enviada
        '400':
          description: Error en la solicitud

  /reset-password/{token}:
    post:
      summary: Restablecer contraseña
      tags:
        - Auth
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                  description: Nueva contraseña del usuario
      responses:
        '200':
          description: Contraseña restablecida exitosamente
        '400':
          description: Error en la solicitud

  /verify-reset-token/{token}:
    get:
      summary: Verificar token de restablecimiento de contraseña
      tags:
        - Auth
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token válido
        '400':
          description: Token inválido

  /verify-email/{token}:
    get:
      summary: Verificar correo electrónico
      tags:
        - Auth
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Correo electrónico verificado exitosamente
        '400':
          description: Token inválido

  /subjects:
    get:
      summary: Obtener todas las materias del usuario autenticado
      tags:
        - Subjects
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de materias obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subject'
        '401':
          description: No autorizado

    post:
      summary: Crear una nueva materia para el usuario autenticado
      tags:
        - Subjects
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subjectName:
                  type: string
                  description: Nombre de la materia
                description:
                  type: string
                  description: Descripción de la materia
                name_teacher:
                  type: string
                  description: Nombre del profesor
      responses:
        '201':
          description: Materia creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado

  /subjects/{id}:
    put:
      summary: Editar una materia del usuario autenticado
      tags:
        - Subjects
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subjectName:
                  type: string
                  description: Nombre de la materia
                description:
                  type: string
                  description: Descripción de la materia
                name_teacher:
                  type: string
                  description: Nombre del profesor
      responses:
        '200':
          description: Materia actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subject'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado

    delete:
      summary: Eliminar una materia del usuario autenticado
      tags:
        - Subjects
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Materia eliminada exitosamente
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado

  /activities/{id}:
    get:
      summary: Obtener todas las actividades de una materia específica
      tags:
        - Activities
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de actividades obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
        '401':
          description: No autorizado

    post:
      summary: Crear una nueva actividad en una materia específica
      tags:
        - Activities
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
      responses:
        '201':
          description: Actividad creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado

    put:
      summary: Actualizar una actividad existente
      tags:
        - Activities
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActivityRequest'
      responses:
        '200':
          description: Actividad actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado

    delete:
      summary: Eliminar una actividad existente
      tags:
        - Activities
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Actividad eliminada exitosamente
        '400':
          description: Error en la solicitud
        '401':
          description: No autorizado
